title:            Stefan Mai
tagline:          The personal blog of Stefan Mai.
description:      The personal blog of Stefan Mai.
url:              https://www.iamnafets.com
baseurl:          ""

# Owner/author information
owner:
  name:           Stefan Mai
  avatar:         profile.jpg
  bio: >-
    I’m Stefan Mai, cofounder of <a href="https://www.hellointerview.com">Hello Interview</a>,
    software engineer, and dad of three. This is where I write things down and occasionally
    change my mind.
  email:          iamnafets@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter: iamnafets        
  facebook:       
  github: iamnafets         
  linkedin: stefanmai
  instagram:      
  lastfm:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:        

# Links to include in top navigation
# For external links add external: true
links:
  - title: Posts
    url: /posts/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Los_Angeles
future:      true
highlighter: rouge
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "README.md", "Gemfile", "Gemfile.lock"]
